### PR TITLE
ci/incrementalbuild: try git clean, if git am fails

### PR DESCRIPTION
**Pull request by evelikov**
Consider the following scenario:
 - build process produces file FOO
 - new patch is applied, which introduces FOO
 - git am invocation fails, since file is already in-tree

To address this problem, issue `git clean -d --force -x`. We are using lowercase x here, since the file is not guaranteed to be listed in .gitignore.

---

This is a blind attempt to fix https://github.com/BluezTestBot/bluez/pull/2090#issuecomment-1949515120

Saying blind, because trying to replicate the whole CI is kind of impossible. In particular I suspect this may miss-fire, if we're saving the patch files or other metadata, within the git repository itself.

@tedd-an @Vudentz can we get all the CI components moved into the https://github.com/bluez namespace? Currently we have bits all over the place - some in https://github.com/BluezTestBot/ and others in https://github.com/tedd-an/. The linux-bluetooth gets a summary email (which is great), although relating that to the 1) github action/respective source code and 2) full log is a huge time sink.

### CODE REVIEW

**Comment by evelikov** [comment]
As a nice side-effect to moving the components under /bluez, one can mode definitively reason and parallelize the CI. Currently all the actions are run sequentially are we're seen 1-2h long jobs. In practise one can cut those in half.

**Comment by evelikov** [comment]
Cross-checked and fixes patch/mbox storage for the actions in `ci`. The `sync_patchwork` should probably be updated to `patch-root` in the future,  atm the script seems out of place wrt the `ci` scripts.

Other artefacts (like the scan-build stderr for example) should also be stored outside the source/git repo. Although that can be done in another PR. Assuming maintainers agree with the idea, of course.

---

This PR should not cause regressions, even though it is still untested.

Undrafting since it should work (tm). Please err on the cautious side while reviewing.

**Comment by Vudentz** [comment]
@tedd-an doesn't looks like I have permission to push this one.
@evelikov I agree we need to start pushing the CI to the main tree, perhaps we can start moving the scripts to the main tree so we don't have to keep maintaining it in different places.

**Comment by evelikov** [comment]
@Vudentz from memory (it's been a few months sorry) the existing CI depends on extra infra to a) send the emails and b) administrative account for the patchwork instance.

The way I see it we need to either a) borrow @tedd-an to migrate the repositories (don't think that merging them in bluez is wise move) and grant someone the s3cr1t stuff or b) start from scratch with a in-bluez .github/.gitlab CI.

**Pull request merged**
